rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.3.0
env: TEST=true
notifications:
  slack:
    secure: SJn1oaxNBtYfT3vDMY82Q4l8m2QlDfiLGwY4/N+5RNdw5u03ebAjoiuGrzcbWGRxt7eiFQjH/EyApq4f1WkB1jARdOg7I45IOIH1PEcks2U5PEqtRidNR/7ySm8UjAkDnXviZPhhBaUOCgQNNIl4zvLUnGKAJYTUvub2owWkGzT1pamewFq4JznPPpdzHW3BcAk/lo5a+vvLTIIeHwwYfcsRZYf+C3Q/Ii+S8RgXn8uAQ+TIv2uRR3o/whnnGXPghEUkBraS+KAdd46k9iEuL1D2DvogwGbPg0Rvd+g3LzpIKhVAvV1lIPiwBDXGeUYGgM5b2GcPVbpI/ktEeHKokIdKn9LpBQ1d63KQ2Sx23ggP2mXoF+0UIDZWiS9mG7UYyrf2YAps8/EPvist1AIJuu9UCs7Wxi+r3MaeBM/CM5vMLToTq3uWaBtbctIQl8DUslnC6m1kL4vPwKureMYQX1DssIZ5kyOkHNEHwKdre3j7R/9tWdWOgPotozACUNovOHh9a3DZusYZcFx+H56/SKIEnD50TNY3DguJbNwEdGHqhwQ/aql04qg/4jXfT5hnPNqLVzq+T+wu85t53CQP/+0PP/Rt7JZo9/CE9n1jEF7UrQbJRuyBCqkJU5+mkjVYM3wVgs9m1TFG+Y6sJyBrMd+W5aG0BM1QZ7QofX/pQN0=
